package tessera.editor

/** User-visible text, in one place for a later translation. French for now. */
object Strings {
    const val modeFrames = "Cases"
    const val modeTexts = "Textes"
    const val modeInfo = "Informations"
    const val nextStep = "Prochaine étape"
    const val read = "Lire"
    const val readHint = "Lire case par case (Espace)"
    const val save = "Enregistrer"
    const val cover = "Couv."
    const val coverPage = "Couverture"
    const val frames = "Cases"
    const val page = "Planche"
    const val inFile = "Dans le fichier"
    const val inFileNote = "Seuls les attributs points modifiés changent ; tout le reste du fichier est réécrit à l’octet près."
    const val background = "Fond"
    const val transition = "Transition"
    const val transitionDefault = "Par défaut (fondu)"
    const val autoOrder = "Ordre auto"
    const val leftToRight = "Gauche → droite"
    const val rightToLeft = "Droite → gauche"
    const val direction = "Sens"
    const val rectangle = "Rectangle"
    const val noFrames = "Aucune case. Tracez-en une avec R, ou cliquez point par point avec P."
    const val fit = "Ajuster"
    const val orderNeedsTwo = "Il faut au moins deux cases"
    const val threePointsMinimum = "Une case garde au moins trois points"
    const val orderSaved = "Ordre de lecture enregistré"
    const val autoOrderLtr = "Ordre : lignes de haut en bas, de gauche à droite"
    const val autoOrderRtl = "Ordre : lignes de haut en bas, de droite à gauche"
    const val nothingToSave = "Rien à enregistrer"
    const val noFramesToRead = "Aucune case à lire"
    const val close = "Fermer"
    const val imageMissing = "Image introuvable"
    const val toolSelect = "Sélection (V)"
    const val toolRect = "Rectangle (R)"
    const val toolPoly = "Polygone (P)"
    const val toolOrder = "Ordre de lecture (O)"
    const val validate = "Valider"
    const val cancel = "Annuler"
    const val inherited = "hérité"

    fun pageOf(n: Int, total: Int) = "Planche $n sur $total"
    fun polygon(points: Int) = "Polygone · $points points"
    fun frameOf(n: Int, total: Int) = "Case $n / $total"
    fun orderProgress(done: Int, total: Int) = "Ordre de lecture : $done / $total"
    fun saved(addedAcbf: Boolean) = if (addedAcbf) "Enregistré : fichier ACBF ajouté au CBZ" else "Enregistré : seul le fichier ACBF a changé"
    fun saveFailed(reason: String?) = "Enregistrement impossible : ${reason ?: "erreur inconnue"}"
}
