#!/usr/bin/env python3
"""
Extracts the convolution weights of Anime4K's CNN shaders (MIT licence, github.com/bloc97/Anime4K)
into editor/src/enhance/Anime4KModels.kt, for Tessera's pure-Kotlin inference engine.

    tools/anime4k_weights.py ref/anime4k     # a clone of the Anime4K repository

Each shader pass is a sum of terms `mat4(...) * input(x, y)` plus a bias. An input is the page
(MAIN) or the output of an earlier pass, taken as is, as max(v, 0) or as max(-v, 0) (CReLU).
The last pass is followed by either a residual added to the page (Restore) or a depth-to-space
step that doubles the resolution and adds to the bilinearly enlarged page (Upscale).
"""
import base64, re, struct, sys
from pathlib import Path

MODELS = {
    "RESTORE_M": "glsl/Restore/Anime4K_Restore_CNN_M.glsl",
    "UPSCALE_X2_M": "glsl/Upscale/Anime4K_Upscale_CNN_x2_M.glsl",
}

def parse(path):
    text = Path(path).read_text()
    passes = []
    for block in text.split("//!DESC ")[1:]:
        desc = block.splitlines()[0]
        save = re.search(r"//!SAVE (\S+)", block).group(1)
        if "Depth-to-Space" in desc:
            passes.append({"kind": "d2s"})
            continue
        defines = {}
        for name, body in re.findall(r"#define (g\w*_\d+)\(?[^)]*?\)? \((.*)\)\s*$", block, re.M):
            m = re.match(r"max\(\(?(-?)\(?(\w+?)_tex(Off)?\(", body)
            if m:
                act = 2 if m.group(1) == "-" else 1
                src = m.group(2)
            else:
                m = re.match(r"(\w+?)_tex(Off)?\(", body)
                act, src = 0, m.group(1)
            defines[name] = (src, act)
        terms, bias = [], None
        for line in block.splitlines():
            line = line.strip()
            m = re.match(r"(?:vec4 result =|result \+=) mat4\(([^)]*)\) \* (\w+)(?:\(([-\d.]+), ([-\d.]+)\))?;", line)
            if m:
                values = [float(v) for v in m.group(1).split(",")]
                src, act = defines[m.group(2)]
                dx = int(float(m.group(3))) if m.group(3) else 0
                dy = int(float(m.group(4))) if m.group(4) else 0
                terms.append((src, act, dx, dy, values))
                continue
            m = re.match(r"result \+= vec4\(([^)]*)\);", line)
            if m:
                bias = [float(v) for v in m.group(1).split(",")]
        residual = "+ MAIN_tex(MAIN_pos)" in block
        passes.append({"kind": "conv", "save": save, "terms": terms, "bias": bias, "residual": residual})
    return passes

def kotlin(name, passes):
    # Sources: MAIN is -1, otherwise the index of the pass that saved it.
    saved = {}
    out = []
    for i, p in enumerate(passes):
        if p["kind"] == "d2s":
            out.append(f'        Pass.depthToSpace()')
            continue
        floats = []
        terms = []
        for src, act, dx, dy, values in p["terms"]:
            s = -1 if src == "MAIN" else saved[src]
            terms.append(f"{s},{act},{dx},{dy}")
            floats += values
        floats += p["bias"]
        blob = base64.b64encode(struct.pack("<%df" % len(floats), *floats)).decode()
        out.append(f'        Pass("{";".join(terms)}", "{blob}", residual = {str(p["residual"]).lower()})')
        saved[p["save"]] = i
    return f"    val {name} = Model(\n        \"{name}\",\n" + ",\n".join(out) + ",\n    )\n"

def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "ref/anime4k")
    body = "".join(kotlin(name, parse(root / path)) for name, path in MODELS.items())
    licence = (root / "LICENSE").read_text().strip().splitlines()
    header = "\n".join("// " + l if l else "//" for l in licence)
    src = f"""// Generated by tools/anime4k_weights.py from Anime4K v3.2/v4.0 (github.com/bloc97/Anime4K).
// The weights below are Anime4K's, under its licence:
//
{header}

package tessera.editor.enhance

/** Anime4K's CNN models, as passes for [Cnn]. */
internal object Anime4KModels {{
{body}}}
"""
    out = Path("editor/src/enhance/Anime4KModels.kt")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(src)
    print(out, len(src), "bytes")

main()
